name: Mark and eventually close stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had any recent activity for the last 45 days. It will be closed if no further activity occurs in the next week.'
        stale-pr-message: ' This pull request has been automatically marked as stale because it has not had any recent activity for the last 45 days. It will be closed if no further activity occurs in the next week. '
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-label: 'waiting'
        exempt-pr-label: 'waiting'
        days-before-stale: 45
        days-before-close: 7
